<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Kembali_confirm-block</name>
   <tag></tag>
   <elementGuidId>530bd5c6-56de-4663-ad43-f8e7f7e3b0af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='confirm-block']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#confirm-block</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4b2b6353-03eb-4ffe-9074-4d314724207c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>confirm-block</value>
      <webElementGuid>685689b4-e658-46df-9467-4537b1d3ebbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>px-4 py-3 w-1/2 font-medium bg-[#CB3A31] hover:bg-[#BD251C] active:bg-[#731912] text-white rounded-xl ml-2</value>
      <webElementGuid>762e9bc1-8a50-41c5-a668-a003e3398789</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Block</value>
      <webElementGuid>206b4db2-7224-4638-bfb4-c06d558babbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;confirm-block&quot;)</value>
      <webElementGuid>86395cd8-003e-4f96-8d39-c6715a62e6a9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='confirm-block']</value>
      <webElementGuid>2f439114-a8af-460b-bf9c-9da3f32007b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='block-popup']/div/div/button[2]</value>
      <webElementGuid>cd7fa793-a984-43ef-9698-4989d0910228</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kembali'])[2]/following::button[1]</value>
      <webElementGuid>2e180e29-03ba-49d2-9b34-0be322e89d71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Block Postingan ini?'])[1]/following::button[2]</value>
      <webElementGuid>34b34e33-8127-4123-a4ff-9698d7cc9f95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reject Postingan ini?'])[1]/preceding::button[1]</value>
      <webElementGuid>44711bfc-d8e6-408c-b093-f1e06c45932f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kembali'])[3]/preceding::button[1]</value>
      <webElementGuid>6ee08efe-467c-47fc-93b1-9d49833ec254</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Block']/parent::*</value>
      <webElementGuid>d73602de-361a-4000-b2a6-599a7678bc73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/button[2]</value>
      <webElementGuid>29992af2-ff86-42d0-ac36-e1c384171c14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'confirm-block' and (text() = 'Block' or . = 'Block')]</value>
      <webElementGuid>0453a568-7922-4e19-93c5-ac3fb1662da6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
