<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>canvas_Kecamatan di KABUPATEN BLITAR_totalA_5727e1</name>
   <tag></tag>
   <elementGuidId>9348213e-e0eb-49f5-9d96-139a766181ce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#totalAnggotaByProvinceChart</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//canvas[@id='totalAnggotaByProvinceChart']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#totalAnggotaByProvinceChart</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>canvas</value>
      <webElementGuid>7c5c84e6-f97c-4cbe-a29e-62b36e662221</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>totalAnggotaByProvinceChart</value>
      <webElementGuid>e5254204-9f04-4608-86f9-ae1caf7f7f1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>261</value>
      <webElementGuid>b5db44eb-0a5f-43ed-a49f-845b82bdd9ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>130</value>
      <webElementGuid>041fa35b-d859-4c47-85b9-1b14e26413e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;totalAnggotaByProvinceChart&quot;)</value>
      <webElementGuid>65c097a2-be46-45c8-8f4f-a06bcc39c50c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//canvas[@id='totalAnggotaByProvinceChart']</value>
      <webElementGuid>d1fbca83-ed29-4536-a92c-9e0d708802e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/canvas</value>
      <webElementGuid>013e009c-fb2f-4ff7-9cbb-6a74400c0c2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//canvas[@id = 'totalAnggotaByProvinceChart']</value>
      <webElementGuid>5e77a211-2e89-4b31-bca8-f933e81af360</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
