<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Version_shrink-button</name>
   <tag></tag>
   <elementGuidId>d5fe58a3-66ed-460e-9226-4556dca6d10e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#shrink-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='shrink-button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=img[name=&quot;Shrink Icon&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>7e7c9dbc-67ed-4179-9792-28e30cb1ce97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>shrink-button</value>
      <webElementGuid>78f1a461-fb9f-41dd-9c0e-6465a2c1c751</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://app-sumu.wins.web.id/assets/sidebar/img/shrink-button.png</value>
      <webElementGuid>d826ec5e-e6b7-49c4-ae81-1ffe3905affe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Shrink Icon</value>
      <webElementGuid>4c218b2d-f1b0-42f6-90c4-dace4ffccbb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>absolute right-[-20%] top-0 ml-5 w-32 h-32 cursor-pointer</value>
      <webElementGuid>ebc294f1-5b84-441e-a9df-5f14a19f5ccc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;shrink-button&quot;)</value>
      <webElementGuid>24a6d6f3-c7dd-4275-be33-ab977fd94b16</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='shrink-button']</value>
      <webElementGuid>d5c64ba1-f24d-49f8-bc21-c92d7f85e65e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//aside[@id='default-sidebar']/div/img</value>
      <webElementGuid>7ae52dd8-2e83-4cb4-b68e-f44570046b37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Shrink Icon']</value>
      <webElementGuid>41842260-c011-46ee-a902-c4717ffc841e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/img</value>
      <webElementGuid>e11a45e7-d52e-4030-aa9d-722083624198</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'shrink-button' and @src = 'https://app-sumu.wins.web.id/assets/sidebar/img/shrink-button.png' and @alt = 'Shrink Icon']</value>
      <webElementGuid>dd8ef6a8-33f1-46ec-9295-b454c4b9510d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
