<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_active_w-5 h-5 cursor-pointer</name>
   <tag></tag>
   <elementGuidId>a258dabb-9ead-4c2f-a4a0-2e6bba191cc4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//img[@alt='Edit'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>4dc28da4-d17b-4aee-90b9-550f9b93b7e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://app-sumu.wins.web.id/assets/pengguna/edit.png</value>
      <webElementGuid>ebf7e0ac-bcdc-4692-a10b-9db750a22615</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Edit</value>
      <webElementGuid>3e3f7126-ef5a-4eca-ba8b-ede119fcc850</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-5 h-5 cursor-pointer</value>
      <webElementGuid>264b33a0-f40e-4cc9-b0fa-7f0f511199e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;flex flex-col min-h-screen bg-gray-100&quot;]/main[@class=&quot;flex-grow p-4 sm:ml-80&quot;]/div[@class=&quot;container p-4 mx-auto&quot;]/div[@class=&quot;w-full pb-4 mt-12 bg-white shadow-lg rounded-3xl&quot;]/div[@class=&quot;overflow-x-auto&quot;]/table[@class=&quot;min-w-full mt-4 border-collapse&quot;]/tbody[@class=&quot;text-gray-700 bg-white&quot;]/tr[@class=&quot;border border-gray-200&quot;]/td[@class=&quot;flex items-center justify-center px-2 py-3 space-x-3 text-sm&quot;]/a[@class=&quot;flex-shrink-0&quot;]/img[@class=&quot;w-5 h-5 cursor-pointer&quot;]</value>
      <webElementGuid>aad7582d-37d0-429f-804e-87e71e0030a9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='Edit'])[2]</value>
      <webElementGuid>b2b078f5-86d5-4157-939c-d75af077a998</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[4]/a/img</value>
      <webElementGuid>2b8d4cf7-aaae-49b9-8adc-2a552be7ad46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://app-sumu.wins.web.id/assets/pengguna/edit.png' and @alt = 'Edit']</value>
      <webElementGuid>3826fcdb-3e54-4cac-a2c0-bcc1e4894067</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
