<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Administrator_menu-text</name>
   <tag></tag>
   <elementGuidId>945ca32d-e9eb-4eca-8ef0-bdeb25efa272</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#menu-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='menu-text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Dashboard Icon Dashboard&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>282be18f-4298-4f03-8720-2936cf798b0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>menu-text</value>
      <webElementGuid>eab584ef-7ef4-448a-af2b-1b427b434f30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ml-3</value>
      <webElementGuid>fc8c521d-b702-4d52-9471-e37c7e98b29f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Dashboard</value>
      <webElementGuid>a80c061d-3e3c-4686-ac05-a5ff3ce2987f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sidebar-nav&quot;)/li[1]/a[@class=&quot;flex items-center p-2 text-base font-bold  text-gray-500 hover:bg-[#EEF6EC] hover:text-[#54A444]  rounded-lg group transition duration-75&quot;]/span[@id=&quot;menu-text&quot;]</value>
      <webElementGuid>f0d53cb6-18ee-4157-b268-b8273b8872c2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='menu-text']</value>
      <webElementGuid>b623d5f6-337a-4117-baed-922cb5455cd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='sidebar-nav']/li/a/span</value>
      <webElementGuid>876d1cb5-dabf-45a0-aca7-0257e50f366e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Administrator'])[1]/preceding::span[1]</value>
      <webElementGuid>27b8c292-bbcf-4c5d-a9e4-55f7d3b6e1f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Dashboard']/parent::*</value>
      <webElementGuid>06edacb5-d9a6-45d3-b403-dbce5a91dd02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span</value>
      <webElementGuid>345d14f7-cd2b-4d23-aea5-f42d682cd2b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'menu-text' and (text() = 'Dashboard' or . = 'Dashboard')]</value>
      <webElementGuid>3df2a459-0654-4a7f-a135-9fd5ae2b18de</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
