<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Permission_menu-text</name>
   <tag></tag>
   <elementGuidId>d4413fb1-4207-455b-9c0d-cbadd3ed835d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//span[@id='menu-text'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Pengguna Icon Pengguna&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>fbe5d4e9-1632-48b5-8475-3b259eb2f0f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>menu-text</value>
      <webElementGuid>51da10d3-2a9b-418b-bf45-8adbdbccc7c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex-1 ml-3 text-left whitespace-nowrap</value>
      <webElementGuid>fa8dc568-443b-47d4-a980-e07c3bf6e80a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pengguna</value>
      <webElementGuid>e90c884c-8494-4c77-bc4e-6713d3f2f5fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sidebar-nav&quot;)/li[3]/button[@class=&quot;flex items-center w-full p-2 text-base font-bold  text-gray-500  transition duration-75 rounded-lg hover:bg-[#EEF6EC] hover:text-[#54A444] group active:bg-[#EEF6EC] active:text-[#54A444]&quot;]/span[@id=&quot;menu-text&quot;]</value>
      <webElementGuid>c867cdaf-e60e-427e-8d01-a29f496f8797</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//span[@id='menu-text'])[3]</value>
      <webElementGuid>45ede796-efea-4b1c-abf8-5fe680a405ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='sidebar-nav']/li[3]/button/span</value>
      <webElementGuid>036b4c31-2078-40ed-8991-37297c0016ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Permission'])[1]/following::span[1]</value>
      <webElementGuid>f2d551ee-c47b-4ad9-8a4f-5f60b6be929e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar Pengguna'])[1]/preceding::span[1]</value>
      <webElementGuid>a85bc242-489a-4f87-87ae-c47cee8c2a92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Verifikasi Pengguna'])[1]/preceding::span[1]</value>
      <webElementGuid>e3d340f8-87b2-4128-ba75-9486f6c2eeed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Pengguna']/parent::*</value>
      <webElementGuid>7bad6b6a-a8c7-42ca-8866-e21b283dc915</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/button/span</value>
      <webElementGuid>446d07ad-79e3-4dca-91e7-8f94b1f6988c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'menu-text' and (text() = 'Pengguna' or . = 'Pengguna')]</value>
      <webElementGuid>2fb3cdea-e97c-4efb-908e-e04eb297f3ba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
