<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Block_w-6 h-6 cursor-pointer</name>
   <tag></tag>
   <elementGuidId>a500cdc5-f305-46e9-ae8b-2e7655a44d88</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='View']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.w-6.h-6.cursor-pointer</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>f5f44e9f-5e28-4ad4-9df6-83046a988107</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://app-sumu.wins.web.id/assets/postingan/img/eye.png</value>
      <webElementGuid>bb8c5acf-7565-4abd-867e-eca696cd0f92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>View</value>
      <webElementGuid>e02e8f22-6646-4922-ab3a-d853897f0f91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-6 h-6 cursor-pointer</value>
      <webElementGuid>6fdfa485-3593-4668-a962-e5b963771358</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;flex flex-col min-h-screen bg-gray-100&quot;]/main[@class=&quot;flex-grow p-4 sm:ml-80&quot;]/div[@class=&quot;container p-4 mx-auto&quot;]/div[@class=&quot;w-full pb-4 mt-12 bg-white shadow-lg rounded-3xl&quot;]/div[@class=&quot;overflow-x-auto&quot;]/table[@class=&quot;min-w-full mt-4 border-collapse&quot;]/tbody[@class=&quot;text-gray-700 bg-white&quot;]/tr[@class=&quot;border border-gray-200&quot;]/td[@class=&quot;flex items-center justify-between px-6 py-4 pr-12 space-x-1 text-sm border border-gray-200&quot;]/a[@class=&quot;flex-shrink-0 w-10 md:w-auto&quot;]/img[@class=&quot;w-6 h-6 cursor-pointer&quot;]</value>
      <webElementGuid>187556f1-df59-4f60-8765-8280118d05cf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='View']</value>
      <webElementGuid>bacc9ef7-007d-4972-9180-339a8ecf1ea5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[9]/a/img</value>
      <webElementGuid>cd4d4660-85e0-4f12-969b-5187bbc30a7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://app-sumu.wins.web.id/assets/postingan/img/eye.png' and @alt = 'View']</value>
      <webElementGuid>9ce23057-6a61-4801-b953-8b0833218c5f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
