<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Permission_menu-text</name>
   <tag></tag>
   <elementGuidId>cda52302-e618-47e6-931a-c884529a1908</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//span[@id='menu-text'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Pengguna Icon Pengguna&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>487d150f-f2dc-4b0c-a69d-3d66237dd4ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>menu-text</value>
      <webElementGuid>329231cf-2697-4fde-a75f-614a1bb8e723</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex-1 ml-3 text-left whitespace-nowrap</value>
      <webElementGuid>799f1936-a6bb-4763-91a8-ac14024a956d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pengguna</value>
      <webElementGuid>bc79cf1e-91cd-4bb3-ae35-5d1897a85384</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sidebar-nav&quot;)/li[3]/button[@class=&quot;flex items-center w-full p-2 text-base font-bold  text-gray-500  transition duration-75 rounded-lg hover:bg-[#EEF6EC] hover:text-[#54A444] group active:bg-[#EEF6EC] active:text-[#54A444]&quot;]/span[@id=&quot;menu-text&quot;]</value>
      <webElementGuid>ff05ee4b-db7e-43b9-9e32-d5ae3165c370</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//span[@id='menu-text'])[3]</value>
      <webElementGuid>5b3be026-47a2-4a2a-bae2-b8f2690a42ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='sidebar-nav']/li[3]/button/span</value>
      <webElementGuid>e97bafa3-d193-4825-9cf7-30937ba884a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Permission'])[1]/following::span[1]</value>
      <webElementGuid>e62ec0c2-d31c-48c3-84f6-8da654ca197d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar Pengguna'])[1]/preceding::span[1]</value>
      <webElementGuid>e9459ae6-bdab-4b1b-a7cf-baf9e0d0f3a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Verifikasi Pengguna'])[1]/preceding::span[1]</value>
      <webElementGuid>895a6970-89cd-4834-b6c7-7099fa036b7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Pengguna']/parent::*</value>
      <webElementGuid>03a62304-fa67-46c5-8588-36d629c161cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/button/span</value>
      <webElementGuid>6ba1eff8-da4a-485f-bc0a-7dee1e6e5b66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'menu-text' and (text() = 'Pengguna' or . = 'Pengguna')]</value>
      <webElementGuid>ec964be4-4817-4084-972d-8432b4b6de07</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
