<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>canvas</name>
   <tag></tag>
   <elementGuidId>5faccc9f-5a75-4998-a3a7-b7d6d5b70b5b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#chartPendaftar > div > canvas</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='chartPendaftar']/div/canvas</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>canvas</value>
      <webElementGuid>dd10f6e2-4473-41b5-927f-667c7ffe9ec4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-zr-dom-id</name>
      <type>Main</type>
      <value>zr_0</value>
      <webElementGuid>5ed9dc06-9758-4f27-921c-167055308bfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>871</value>
      <webElementGuid>4be277b4-11f9-4e77-8903-82a0b0d3c46f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>480</value>
      <webElementGuid>cbc10dfd-25c1-4b18-b6ca-ce7e438e95fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chartPendaftar&quot;)/div[1]/canvas[1]</value>
      <webElementGuid>9640c2bb-b7fa-48ef-a9be-3855072638e9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='chartPendaftar']/div/canvas</value>
      <webElementGuid>846b51ed-4f61-4c5d-9c60-25145d25816b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/canvas</value>
      <webElementGuid>dae9f3ca-0266-4f81-8fb4-fca241fc6f81</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
