<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Verifikasi Pengguna_menu-text</name>
   <tag></tag>
   <elementGuidId>cfbb626e-e4ec-4fdd-ad3e-6c50db8c85b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//span[@id='menu-text'])[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>4970fb55-b01a-4c43-9569-f70266e7db7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>menu-text</value>
      <webElementGuid>935d835c-fb56-47ee-9c23-b5d3477b7625</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex-1 ml-3 text-left whitespace-nowrap</value>
      <webElementGuid>8973aed2-7c9a-4a63-852f-42ebc02f7f3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Postingan</value>
      <webElementGuid>e483f34c-022f-4429-a426-cc06c0de46d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sidebar-nav&quot;)/li[4]/button[@class=&quot;flex items-center w-full p-2 text-base font-bold  text-gray-500  transition duration-75 rounded-lg hover:bg-[#EEF6EC] hover:text-[#54A444] group active:bg-[#EEF6EC] active:text-[#54A444]&quot;]/span[@id=&quot;menu-text&quot;]</value>
      <webElementGuid>769e5312-b45f-4fda-be79-ecc6c868db5e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//span[@id='menu-text'])[4]</value>
      <webElementGuid>87c389ab-d17c-4344-a0b3-0e9937119513</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='sidebar-nav']/li[4]/button/span</value>
      <webElementGuid>5be17c65-496b-40fb-bcc6-fa9d6b7dd3b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Verifikasi Pengguna'])[1]/following::span[1]</value>
      <webElementGuid>5e928e2a-2a54-49de-81dd-f74ad1829e41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar Pengguna'])[1]/following::span[1]</value>
      <webElementGuid>be0b8c4b-7e76-4d74-8219-92ee3e9bd1ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Postingan'])[2]/preceding::span[1]</value>
      <webElementGuid>a2bb4eda-c911-4403-8e07-88717ca12fd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Postingan']/parent::*</value>
      <webElementGuid>c4d29a60-1f91-4bfc-aa2f-480acce004f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/button/span</value>
      <webElementGuid>a8852112-fe4d-4957-9495-551df37e2339</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'menu-text' and (text() = 'Postingan' or . = 'Postingan')]</value>
      <webElementGuid>81fa0d9c-2ec7-421a-9bc4-f31e37b9f3cd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
