<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Postingan_font-lato px-4 py-2 text-sm tex_f03616</name>
   <tag></tag>
   <elementGuidId>8dcb4c98-fd4f-4d09-b10d-5c4cf80e7bb6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Create')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>829454f9-a31e-4e43-a250-5eba675b6d6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://app-sumu.wins.web.id/postingan/postingan/create</value>
      <webElementGuid>1d864a36-973d-481c-aef8-e41baa3d7082</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>font-lato px-4 py-2 text-sm text-center text-white bg-[#54A444] rounded-xl hover:bg-[#3B7330] active:bg-[#182B23]</value>
      <webElementGuid>73127717-fced-4b23-bec2-0ffd707dfca3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                    Create
                </value>
      <webElementGuid>77577bab-68bc-489b-ba4c-267d2687d1d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;flex flex-col min-h-screen bg-gray-100&quot;]/main[@class=&quot;flex-grow p-4 sm:ml-80&quot;]/div[@class=&quot;container p-4 mx-auto&quot;]/div[@class=&quot;flex items-center justify-between mb-4&quot;]/div[@class=&quot;flex space-x-4&quot;]/a[@class=&quot;font-lato px-4 py-2 text-sm text-center text-white bg-[#54A444] rounded-xl hover:bg-[#3B7330] active:bg-[#182B23]&quot;]</value>
      <webElementGuid>0c74dd2c-cb3a-453f-9daf-3e51d3251f15</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Create')]</value>
      <webElementGuid>64ab2f1a-25eb-4172-babf-28cb0d113df8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Postingan'])[6]/following::a[1]</value>
      <webElementGuid>9dc391b3-5231-457a-b432-8e658db1e698</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Keluar'])[2]/following::a[1]</value>
      <webElementGuid>b00926df-08a3-4d90-8c14-e3226e2564a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[1]/preceding::a[1]</value>
      <webElementGuid>72323545-c3e4-4bce-bebd-dec2e97101bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Create']/parent::*</value>
      <webElementGuid>1c097b26-ae72-4341-afed-906b308bf0ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://app-sumu.wins.web.id/postingan/postingan/create')]</value>
      <webElementGuid>67d8dab1-fa22-448d-a0ca-b122ed99b242</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//main/div/div/div/a</value>
      <webElementGuid>249373d3-d8d6-4c4b-a73c-ef566728ddd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://app-sumu.wins.web.id/postingan/postingan/create' and (text() = '
                    Create
                ' or . = '
                    Create
                ')]</value>
      <webElementGuid>51add79c-669f-47cc-ad0e-16dea515dab3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
