<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_SUMU Admin_keluarButton</name>
   <tag></tag>
   <elementGuidId>10f48860-121e-41e6-b21b-1f43181a9971</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='keluarButton']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#keluarButton</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Keluar&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2efb99dc-ebe2-46e4-9bab-638e8bc6bcb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://app-sumu.wins.web.id/logout</value>
      <webElementGuid>93d98fda-2dbd-4585-9cb3-10cadc430565</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>keluarButton</value>
      <webElementGuid>28adfdf7-9f69-4901-8047-90bff8852643</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>block px-4 py-2 mx-auto text-center text-gray-800 border border-gray-300 rounded-xl hover:bg-[#EEF6EC] hover:text-[#54A444] w-[85%] mb-4 mt-2</value>
      <webElementGuid>cc19b064-2ed3-4add-b318-a7b1a7bfecfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                    Keluar
                </value>
      <webElementGuid>48c8ba4c-d69c-47af-aeac-bcd62765cd5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;keluarButton&quot;)</value>
      <webElementGuid>567c7928-cedc-408c-a535-b7d78a562629</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='keluarButton']</value>
      <webElementGuid>d229c1ed-4870-449f-aa65-10b9b52513b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='avatarDropdown']/a[2]</value>
      <webElementGuid>c9b5eedb-678d-4be8-b018-884a969ee44f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Keluar')]</value>
      <webElementGuid>eac7d055-2ede-4945-9a64-06909c5bfcc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Admin@sumu.or.id'])[1]/following::a[2]</value>
      <webElementGuid>fdfb36ac-cd20-4f7c-a994-88bb35aa3578</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ingin Keluar?'])[1]/preceding::a[1]</value>
      <webElementGuid>3bf50213-aa3f-42c0-9a55-efa8008bb530</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kembali'])[1]/preceding::a[1]</value>
      <webElementGuid>2a790a1e-a08d-4470-9e18-2969262fa3b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Keluar']/parent::*</value>
      <webElementGuid>4fe7f858-f55b-48bb-8557-fbe8d19533b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://app-sumu.wins.web.id/logout')]</value>
      <webElementGuid>841966a6-d905-4223-961c-7af601d44292</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]</value>
      <webElementGuid>cb0bbb1d-d9af-4959-bcdd-1595385506d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://app-sumu.wins.web.id/logout' and @id = 'keluarButton' and (text() = '
                    Keluar
                ' or . = '
                    Keluar
                ')]</value>
      <webElementGuid>6d0e5f42-35d4-499c-b3fe-58da72857e7d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
