<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Kembali_confirmKeluar</name>
   <tag></tag>
   <elementGuidId>cb7e569d-6ad5-4d2b-aef8-b4b9a3367f0d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='confirmKeluar']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#confirmKeluar</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Keluar&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>060a3516-e144-4835-9b5e-e55df4321d4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>confirmKeluar</value>
      <webElementGuid>10137483-16e6-4ce4-a1ef-b3583185aaf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>px-4 py-3 w-1/2 font-medium bg-[#CD7B2E] hover:bg-[#BD251C] active:bg-[#731912] text-white rounded-xl ml-2</value>
      <webElementGuid>11dc2e8a-5008-4689-821a-a68951512da6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Keluar</value>
      <webElementGuid>0baab198-ebc2-490e-915d-dffc473ae2f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;confirmKeluar&quot;)</value>
      <webElementGuid>3aaca8b7-71e1-41fa-87b8-42722d1c13b5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='confirmKeluar']</value>
      <webElementGuid>00130886-a27c-4614-a0d9-c3be425c97d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='keluarPopup']/div/div/button[2]</value>
      <webElementGuid>fddae9b3-c4cb-4ac7-9db5-601f1b592b1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kembali'])[1]/following::button[1]</value>
      <webElementGuid>74462a1d-6705-4b12-a1b1-43faa327b735</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ingin Keluar?'])[1]/following::button[2]</value>
      <webElementGuid>2605e676-f8f2-498d-8a03-e097dd46aa76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Role Management'])[4]/preceding::button[1]</value>
      <webElementGuid>1334cbe0-5c7e-44d3-b645-bf8e3cef6798</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create'])[1]/preceding::button[1]</value>
      <webElementGuid>04f4e11d-c068-43f0-8402-fb67dd42242c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/button[2]</value>
      <webElementGuid>ff3f92a9-2089-44b4-9650-e12a09ca356e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'confirmKeluar' and (text() = 'Keluar' or . = 'Keluar')]</value>
      <webElementGuid>1a79ad06-f6ed-415a-8208-92c4d68bac0f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
