<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Gambar Kategori_preview-image</name>
   <tag></tag>
   <elementGuidId>0bb3e928-8c26-47aa-8d70-41ce1972d23e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#preview-image</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='preview-image']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>953fa79b-3110-4246-8609-b93fbdc19bc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>preview-image</value>
      <webElementGuid>181afdb6-3efe-41d7-8733-2d481aa1b678</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://app-sumu.wins.web.id/storage/https://app.sumu.or.id/storage/forum-kategori/ztdg2siDPxlYY8KkDPYd5kiA4oitpTJY9ndhapGo.png</value>
      <webElementGuid>166c71bf-b513-412c-b043-2e13e3f53039</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Add Image</value>
      <webElementGuid>b7d6c022-a090-4896-afdb-b75edb94be3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-[30%] h-[30%] mx-auto cursor-pointer</value>
      <webElementGuid>1edde8e0-9d91-4cc6-866c-e27a4d6d1446</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;preview-image&quot;)</value>
      <webElementGuid>ffdb6c77-aa50-4bfc-9a43-dd3f5539ad3d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='preview-image']</value>
      <webElementGuid>23a73b90-7678-4185-aa14-438b628cce16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Add Image']</value>
      <webElementGuid>1bd771db-2301-4e02-8d2f-6ac79a45cd2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div/div/img</value>
      <webElementGuid>095730a8-5881-4f51-ba83-ece31e5f224f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'preview-image' and @src = 'https://app-sumu.wins.web.id/storage/https://app.sumu.or.id/storage/forum-kategori/ztdg2siDPxlYY8KkDPYd5kiA4oitpTJY9ndhapGo.png' and @alt = 'Add Image']</value>
      <webElementGuid>b05da5a8-427f-4a7f-8928-240e2fee5f25</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
