<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Kembali_confirm-delete</name>
   <tag></tag>
   <elementGuidId>ceeaa52d-782b-41ce-ba63-c4508066e0f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#confirm-delete</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='confirm-delete']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>efd37859-6e2d-4ef6-9440-cc496e9ae3b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>confirm-delete</value>
      <webElementGuid>8e605175-d2cd-4b9e-b62d-93971b21b67d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>px-4 py-3 w-1/2 font-medium bg-[#CB3A31] hover:bg-[#BD251C] active:bg-[#731912] text-white rounded-xl ml-2</value>
      <webElementGuid>b98cea4a-1f5f-4319-9139-e3991094e633</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hapus</value>
      <webElementGuid>55fa31d2-ceef-44a7-a606-ae2679c8c3d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;flex flex-col min-h-screen bg-gray-100&quot;]/main[@class=&quot;flex-grow p-4 sm:ml-80&quot;]/div[@class=&quot;container p-4 mx-auto&quot;]/div[@class=&quot;w-full pb-4 mt-12 bg-white shadow-lg rounded-3xl&quot;]/div[@class=&quot;overflow-x-auto&quot;]/table[@class=&quot;min-w-full mt-4 border-collapse&quot;]/tbody[@class=&quot;text-gray-700 bg-white&quot;]/tr[@class=&quot;border border-gray-200&quot;]/td[@class=&quot;flex items-center justify-between px-2 py-4 text-sm&quot;]/div[@id=&quot;delete-popup&quot;]/div[@class=&quot;w-full max-w-md p-6 text-center bg-white shadow-lg rounded-xl&quot;]/div[@class=&quot;flex justify-between w-full&quot;]/button[@id=&quot;confirm-delete&quot;]</value>
      <webElementGuid>de555bc9-9fac-497b-bf6b-1b39e6cf1761</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='confirm-delete']</value>
      <webElementGuid>7a0c3f33-fd73-4e35-a2c3-5d84447f12a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='delete-popup']/div/div/button[2]</value>
      <webElementGuid>b01f0060-28c5-4b12-9eb4-fe6fd0d424fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kembali'])[2]/following::button[1]</value>
      <webElementGuid>0ec3c418-5a61-460a-b2e9-02185022deb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ingin menghapus ini?'])[1]/following::button[2]</value>
      <webElementGuid>c58dd18c-e689-496d-8925-3441671c0f12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PRM Sukamulya'])[1]/preceding::button[1]</value>
      <webElementGuid>126718a5-a83d-47cc-be4c-ce7217dbf2bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Muhammadiyah'])[2]/preceding::button[1]</value>
      <webElementGuid>d3e7ad4d-7de6-4fe5-aaf6-289cecc89a69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Hapus']/parent::*</value>
      <webElementGuid>778e62a0-ff03-479d-b79d-53be3d79d445</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[8]/div/div/div/button[2]</value>
      <webElementGuid>6a793192-0419-4805-970d-3eab699d2fa5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'confirm-delete' and (text() = 'Hapus' or . = 'Hapus')]</value>
      <webElementGuid>7cf89cb2-e906-46a8-914b-70e0dfe4f531</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
