<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Administrator_menu-text</name>
   <tag></tag>
   <elementGuidId>5d24a372-11fd-4bf9-8e5c-e398df4e9ff7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='menu-text']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Dashboard Icon Dashboard&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b511cefb-6b23-4621-b07f-45489560f411</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>menu-text</value>
      <webElementGuid>11d14538-5fa3-41b1-aa16-c7a42dc6444e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ml-3</value>
      <webElementGuid>bf09a618-598e-42d5-be36-0e42407f371c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Dashboard</value>
      <webElementGuid>12214563-57a5-4dd0-87e9-c520601a00d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sidebar-nav&quot;)/li[1]/a[@class=&quot;flex items-center p-2 text-base font-bold  text-gray-500 hover:bg-[#EEF6EC] hover:text-[#54A444]  rounded-lg group transition duration-75&quot;]/span[@id=&quot;menu-text&quot;]</value>
      <webElementGuid>3b84d9eb-1da7-4568-a74a-c155bc17a57c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='menu-text']</value>
      <webElementGuid>4ed7472c-6bf0-4c19-8e4b-6dd6c9753d18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='sidebar-nav']/li/a/span</value>
      <webElementGuid>302781e8-4ed6-4c0a-80bc-51d123c31782</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Administrator'])[1]/preceding::span[1]</value>
      <webElementGuid>54cdc5b3-bbf8-42c4-8357-713e8686fbed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Dashboard']/parent::*</value>
      <webElementGuid>8aa37a77-a0b9-49ce-8046-091174163a04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span</value>
      <webElementGuid>73dc1da5-8df9-4d93-8c5d-ca7c5c029357</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'menu-text' and (text() = 'Dashboard' or . = 'Dashboard')]</value>
      <webElementGuid>f7685962-757c-4318-a342-ea46356bc22c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
