<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Laporan                               _fffbac</name>
   <tag></tag>
   <elementGuidId>17442c61-b8f0-4d8a-902d-825e336d664d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//span[@id='menu-text'])[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>76205369-d2b7-48ce-8a39-2a2d33e864e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>menu-text</value>
      <webElementGuid>54862650-d93a-4b42-b4e4-578962f5a6d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex-1 ml-3 text-left whitespace-nowrap</value>
      <webElementGuid>3fa9779e-adad-4ce7-8dfc-f8767593888e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Forum</value>
      <webElementGuid>5e29b27d-53c3-45bc-bed5-b1a108978e7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sidebar-nav&quot;)/li[5]/button[@class=&quot;flex items-center w-full p-2 text-base font-bold  text-gray-500  transition duration-75 rounded-lg hover:bg-[#EEF6EC] hover:text-[#54A444] group active:bg-[#EEF6EC] active:text-[#54A444]&quot;]/span[@id=&quot;menu-text&quot;]</value>
      <webElementGuid>c39919e2-1629-4723-8213-70a185012bd5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//span[@id='menu-text'])[5]</value>
      <webElementGuid>e95b8f99-2ae6-48a4-93a9-75a6ec486831</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='sidebar-nav']/li[5]/button/span</value>
      <webElementGuid>57e0710b-fe9d-4ff4-acf8-84fce72afaf9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Postingan'])[2]/following::span[1]</value>
      <webElementGuid>c3ae87c3-da61-4efd-9ef5-f102c20b1472</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forum'])[2]/preceding::span[1]</value>
      <webElementGuid>21e48dc9-1ca0-4068-abdd-2dea2698e07c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Forum']/parent::*</value>
      <webElementGuid>03d5d082-45eb-4306-9ca2-f0addfd588bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/button/span</value>
      <webElementGuid>fac24053-d1aa-441b-87b4-dc6268e95da0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'menu-text' and (text() = 'Forum' or . = 'Forum')]</value>
      <webElementGuid>63209a75-a43e-4d80-b505-7ac0c4435d20</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
