<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Verifikasi Pengguna_menu-text</name>
   <tag></tag>
   <elementGuidId>47285d6e-1abf-468b-a0fc-c8ec518123e4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//span[@id='menu-text'])[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>784880fb-7e11-481e-b1ac-7dc8f559ca4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>menu-text</value>
      <webElementGuid>d8118781-f4f7-4ac5-8c76-f39491a0355a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex-1 ml-3 text-left whitespace-nowrap</value>
      <webElementGuid>9f1ac6ea-97dc-4a38-b508-97877855c971</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Postingan</value>
      <webElementGuid>926f8502-c8e9-4057-b592-40fafed9ac5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sidebar-nav&quot;)/li[4]/button[@class=&quot;flex items-center w-full p-2 text-base font-bold  text-gray-500  transition duration-75 rounded-lg hover:bg-[#EEF6EC] hover:text-[#54A444] group active:bg-[#EEF6EC] active:text-[#54A444]&quot;]/span[@id=&quot;menu-text&quot;]</value>
      <webElementGuid>4ee2175f-4590-4e0e-9322-6a04ea534350</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//span[@id='menu-text'])[4]</value>
      <webElementGuid>c053debf-b399-442d-9cdb-65412ef40182</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='sidebar-nav']/li[4]/button/span</value>
      <webElementGuid>10905440-19c4-4b9e-af81-f11ca9b99ff4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Verifikasi Pengguna'])[1]/following::span[1]</value>
      <webElementGuid>bde78ea7-d764-41c8-8f4b-ca63edb9ea6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar Pengguna'])[1]/following::span[1]</value>
      <webElementGuid>afae44fc-1907-4a63-8c6a-52c4481b711d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Postingan'])[2]/preceding::span[1]</value>
      <webElementGuid>b5a253e4-f3d4-4007-a0be-4f85fb079a46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Postingan']/parent::*</value>
      <webElementGuid>69ca527b-fcf7-4000-bba4-3dc19c1fb2e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/button/span</value>
      <webElementGuid>2b6eb61e-59d1-4243-8fad-e3a0d5c6909d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'menu-text' and (text() = 'Postingan' or . = 'Postingan')]</value>
      <webElementGuid>8be3a65d-2c54-4385-bccd-d9a4595588d7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
