<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Cover Forum_preview-image</name>
   <tag></tag>
   <elementGuidId>ed318917-c735-4f1c-bf5a-ac1321d1f98b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#preview-image</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='preview-image']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>e3799a67-6554-4a08-9e20-81cb59d481c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>preview-image</value>
      <webElementGuid>5e54c182-365b-4522-a994-89074b3b0c55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://app-sumu.wins.web.id/assets/pengguna/add-image.png</value>
      <webElementGuid>9da1dd37-16f7-40a3-87b4-bffdf98d30b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Tambah Gambar</value>
      <webElementGuid>58256218-c97d-43f2-8d39-2912e92f68dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-[30%] h-[30%] mx-auto</value>
      <webElementGuid>50b7c70b-c65f-4c3c-af11-8d49d4475932</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;preview-image&quot;)</value>
      <webElementGuid>1c0ccdac-a2b9-4ceb-adf5-653eaf36f78f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='preview-image']</value>
      <webElementGuid>a5cdf3dc-fc17-4611-b547-7cfa589bce4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='forumForm']/div/div/div/div/label/img</value>
      <webElementGuid>6b4a9337-15a3-4ed8-b446-327cd82ada73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Tambah Gambar']</value>
      <webElementGuid>2e285529-2611-4097-b395-cceaa7bef67b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/img</value>
      <webElementGuid>bec65a45-a67b-4487-b1bc-d2f14fb4bceb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'preview-image' and @src = 'https://app-sumu.wins.web.id/assets/pengguna/add-image.png' and @alt = 'Tambah Gambar']</value>
      <webElementGuid>1a5686da-34be-4b8e-8195-68db57e8720a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
