<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Kategori_category</name>
   <tag></tag>
   <elementGuidId>a07162f7-5ead-4be9-a7d9-ab17e07823fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#category</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='category']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>4ed2ba4d-eec2-48c1-b126-12cada0c7c17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>category</value>
      <webElementGuid>1b3cfddc-6861-422d-a51f-45ac064f93ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>category</value>
      <webElementGuid>9105caf3-1e8b-4144-8357-030c9bdfc30c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mt-1 block w-full border border-gray-300 rounded-md shadow-sm py-2 px-3 focus:outline-none focus:ring-[#54A444] focus:border-[#54A444]</value>
      <webElementGuid>38786a41-ef3b-49b3-ad2b-122e3c76ad20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                    Pilih Kategori
                                                                            Muhammadiyah
                                                                            Hukum
                                                                            Kerjasama
                                                                            Teknologi
                                                                            Pendidikan
                                                                            Bisnis
                                                                    </value>
      <webElementGuid>2da22647-49fb-464e-9eb8-79d1067cff22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;category&quot;)</value>
      <webElementGuid>3b8d14a6-a2fb-4470-b8b3-3a9dc5297e0e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='category']</value>
      <webElementGuid>d813a5c0-3d84-4954-9ce2-feaffa5c7856</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='forumForm']/div/div[2]/div[2]/div/div[2]/select</value>
      <webElementGuid>f53f9bec-ab8b-4aec-a272-23a12c1840ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kategori'])[1]/following::select[1]</value>
      <webElementGuid>5b18f0cf-f389-4a7b-a8f8-43a2c1323f5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[1]/following::select[2]</value>
      <webElementGuid>a06b23b1-7ee4-4964-9f27-e02eb9485b91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forum Privat'])[1]/preceding::select[1]</value>
      <webElementGuid>65eac878-1162-4e60-91f9-f4e6f52ad635</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Batal'])[1]/preceding::select[1]</value>
      <webElementGuid>5aa526cb-d9cd-4580-8601-e87b7ca6254e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/select</value>
      <webElementGuid>e56f171e-e14e-487e-8f72-7e15e1c93f18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'category' and @id = 'category' and (text() = '
                                    Pilih Kategori
                                                                            Muhammadiyah
                                                                            Hukum
                                                                            Kerjasama
                                                                            Teknologi
                                                                            Pendidikan
                                                                            Bisnis
                                                                    ' or . = '
                                    Pilih Kategori
                                                                            Muhammadiyah
                                                                            Hukum
                                                                            Kerjasama
                                                                            Teknologi
                                                                            Pendidikan
                                                                            Bisnis
                                                                    ')]</value>
      <webElementGuid>c3e7dab1-062e-4e78-a43e-6e0592fc5623</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
